In [1]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [2]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
import tensorflow as tf
from tensorflow.keras import backend as k

In [5]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split


In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [7]:

from tensorflow.keras import models

In [8]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import layers


In [9]:
import pandas as pd
import numpy as np
import  nltk #natural language tool kit
import re #regular expression -removing the special characters
from  nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split

In [10]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [11]:
from tensorflow.keras import layers

In [12]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

if os.environ.get('RUNTIME_ENV_LOCATION_TYPE') == 'external':
    endpoint_f6799ad66c264fd895b3f9a54eab8f7f = 'https://s3.us.cloud-object-storage.appdomain.cloud'
else:
    endpoint_f6799ad66c264fd895b3f9a54eab8f7f = 'https://s3.private.us.cloud-object-storage.appdomain.cloud'

client_f6799ad66c264fd895b3f9a54eab8f7f = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='-70u9yy72HGIYfZ5c8Jny2V2CaUGtYON1xQSio5xD_ZW',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url=endpoint_f6799ad66c264fd895b3f9a54eab8f7f)

body = client_f6799ad66c264fd895b3f9a54eab8f7f.get_object(Bucket='amazonkindle-donotdelete-pr-8q1ztvbrd1hqgs',Key='kindle_reviews.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()


Unnamed: 0        asin helpful  overall  \
0           0  B000F83SZQ  [0, 0]        5   
1           1  B000F83SZQ  [2, 2]        4   
2           2  B000F83SZQ  [2, 2]        4   
3           3  B000F83SZQ  [1, 1]        5   
4           4  B000F83SZQ  [0, 1]        4   

                                          reviewText   reviewTime  \
0  I enjoy vintage books and movies so I enjoyed ...   05 5, 2014   
1  This book is a reissue of an old one; the auth...   01 6, 2014   
2  This was a fairly interesting read.  It had ol...   04 4, 2014   
3  I'd never read any of the Amy Brewster mysteri...  02 19, 2014   
4  If you like period pieces - clothing, lingo, y...  03 19, 2014   

       reviewerID                         reviewerName             summary  \
0  A1F6404F1VG29J                           Avidreader  Nice vintage story   
1   AN0N05A9LIJEQ                             critters        Different...   
2   A795DMNCJILA6                                  dot               Oldie   
3  A1FV0SX13TWVXQ  Elaine H. Turley "Montana Songbird"  I really liked it.   
4  A3SPTOKDG7WBLN                   Father Dowling Fan      Period Mystery   

   unixReviewTime  
0      1399248000  
1      1388966400  
2      1396569600  
3      1392768000  
4      1395187200

In [13]:
nltk.download("stopwords")
print(list(df_data_1.columns))

['Unnamed: 0', 'asin', 'helpful', 'overall', 'reviewText', 'reviewTime', 'reviewerID', 'reviewerName', 'summary', 'unixReviewTime']


[nltk_data] Downloading package stopwords to /home/wsuser/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [14]:
from sklearn.feature_extraction.text import CountVectorizer
df=[]
for i in range(0,1000):
    review=df_data_1['reviewText'][i]
    #a)remove un neccessary .,
    review=re.sub('[^a-zA-Z]',' ',review)
    #b) lower case the text
    review=review.lower()
    #c)split the text
    review=review.split()
    #4.stemming
    #5. remove stop words
    ps=PorterStemmer()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    #6.join the splitted data
    review=' '.join(review)
    df.append(review)

cv=CountVectorizer(max_features=9)

In [15]:
x=cv.fit_transform(df).toarray()
print("Outputting Devi")
print(x)

y=df_data_1.iloc[0:1000:,3:4].values
print(y)

Outputting Devi
[[2 0 1 ... 2 0 0]
 [1 0 1 ... 0 0 1]
 [0 0 0 ... 3 2 0]
 ...
 [3 0 0 ... 1 1 0]
 [0 0 0 ... 1 0 0]
 [3 0 1 ... 1 0 0]]
[[5]
 [4]
 [4]
 [5]
 [4]
 [4]
 [4]
 [4]
 [5]
 [4]
 [5]
 [4]
 [3]
 [3]
 [5]
 [5]
 [5]
 [3]
 [5]
 [4]
 [5]
 [2]
 [5]
 [4]
 [5]
 [3]
 [5]
 [3]
 [4]
 [5]
 [5]
 [5]
 [5]
 [4]
 [3]
 [3]
 [3]
 [5]
 [5]
 [2]
 [3]
 [3]
 [2]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]
 [4]
 [3]
 [4]
 [4]
 [5]
 [4]
 [4]
 [5]
 [5]
 [4]
 [5]
 [5]
 [1]
 [1]
 [1]
 [1]
 [3]
 [4]
 [2]
 [1]
 [2]
 [1]
 [5]
 [5]
 [1]
 [4]
 [5]
 [1]
 [5]
 [1]
 [5]
 [5]
 [4]
 [4]
 [1]
 [2]
 [4]
 [4]
 [4]
 [4]
 [3]
 [3]
 [4]
 [4]
 [4]
 [3]
 [4]
 [5]
 [1]
 [4]
 [5]
 [4]
 [5]
 [5]
 [1]
 [5]
 [2]
 [4]
 [5]
 [3]
 [5]
 [3]
 [4]
 [5]
 [5]
 [4]
 [4]
 [1]
 [4]
 [5]
 [1]
 [5]
 [5]
 [5]
 [2]
 [3]
 [3]
 [5]
 [3]
 [3]
 [5]
 [5]
 [5]
 [4]
 [4]
 [3]
 [4]
 [3]
 [4]
 [2]
 [3]
 [4]
 [3]
 [4]
 [2]
 [5]
 [5]
 [5]
 [3]
 [5]
 [5]
 [3]
 [5]
 [1]
 [4]
 [5]
 [4]
 [5]
 [5]
 [5]
 [5]
 [2]
 [4]
 [4]
 [2]
 [5]
 [5]
 [5]
 [1]
 [2]
 [5]

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 9)
(200, 9)
(800, 1)
(200, 1)


In [17]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential, load_model


In [18]:
model = tensorflow.keras.Sequential()
model.add(layers.Dense(input_dim=9, units=1000, kernel_initializer="random_uniform",activation="relu")) # input layer
model.add(layers.Dense(units=9, kernel_initializer="random_uniform", activation="relu")) # 1st hidden layer
model.add(layers.Dense(units= 1, kernel_initializer="random_uniform", activation="sigmoid")) # output layer

In [19]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["acc"])


In [20]:
model.fit(x_train,y_train,batch_size=128,epochs=1)


7/7 [==============================] - 1s 6ms/step - loss: 0.0000e+00 - acc: 0.0398


In [21]:
a="amazo.h5"

In [22]:
pwd

'/home/wsuser/work'

In [23]:
tensorflow.keras.models.save_model(model,a)

In [24]:
!tar -zcvf Amazon_kindlereview.tgz amazo.h5

amazo.h5


In [25]:
ls -1

amazo.h5
Amazon_kindlereview.tgz


In [26]:
!pip install watson-machine-learning-client --upgrade


     |████████████████████████████████| 538 kB 21.0 MB/s eta 0:00:01


In [27]:
!pip install --upgrade "ibm-watson>=5.2.3"


     |████████████████████████████████| 412 kB 27.2 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 68 kB 13.3 MB/s eta 0:00:01
  Created wheel for ibm-watson: filename=ibm_watson-5.3.0-py3-none-any.whl size=408872 sha256=0f868c033a171d64baf0415040d9ccd829a704a5e8d59f4f8ad1b9b4cd514b4d
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/79/7c/1e/3fc8483af029cd8cb8c803eeaf282cbeb60724130d9dca4b83
Successfully built ibm-watson


In [31]:
from ibm_watson_machine_learning import APIClient
wml_credentials = { "url": "https://us-south.ml.cloud.ibm.com",
                  "apikey": "fLZkrtKYV-anuXD4thMMdXlBqeWzwdLaD1tWvvNAhbQ_"
                  }

In [32]:
client = APIClient(wml_credentials)

In [33]:
client

In [34]:
def guide_from_space_name(client,space_name):
    space = client.spaces.get_details()
    return(next(item for item in space['resources']if item['entity']["name"]== space_name)['metadata']['id'])

In [35]:
space_uid = guide_from_space_name(client,'amazon')
print("Space UID = " + space_uid)

Space UID = 92bdb2bf-f0cb-42e6-8883-ef6e1faef647


In [36]:
client.set.default_space(space_uid)

client.software_specifications.list()

software_spec_uid = client.software_specifications.get_uid_by_name("tensorflow_1.15-py3.6")


-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
scikit-learn_0.22-py3.6        154010fa-5b3b-4ac1-82af-4d5ee5abbc85  base
default_r3.6                   1b70aec3-ab34-4b87-8aa0-a4a3c8296a36  base
pytorch-onnx_1.3-py3.6         1bc6029

In [37]:
software_spec_uid


'2b73a275-7cbf-420b-a912-eae7f436e0bc'

In [38]:
!pip install watson-machine-learning-client


In [39]:
model_details = client.repository.store_model(model='Amazon_kindlereview.tgz',
                                              meta_props= {
                                                  client.repository.ModelMetaNames.NAME:"NLP",
                                                  client.repository.ModelMetaNames.TYPE:"keras_2.2.4",
                                                  client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_spec_uid
                                              }) 
model_id = client.repository.get_model_uid(model_details)

Note: Warnings!! :  Model type keras_2.2.4 is deprecated. We recommend you use a supported model type. See Supported Frameworks https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/pm_service_supported_frameworks.html


In [40]:
model_id

'f98fca98-fc46-40d6-9e0c-d214b9b716f2'

In [41]:
ypred=model.predict(x_test)

In [42]:
ypred

array([[0.52458507],
       [0.5235556 ],
       [0.5107308 ],
       [0.51445335],
       [0.55853117],
       [0.5197622 ],
       [0.5452079 ],
       [0.5328865 ],
       [0.5051727 ],
       [0.5282548 ],
       [0.5328206 ],
       [0.59916306],
       [0.5415306 ],
       [0.5148672 ],
       [0.5104259 ],
       [0.54143465],
       [0.5573469 ],
       [0.5110436 ],
       [0.5169665 ],
       [0.5440804 ],
       [0.5197655 ],
       [0.53591824],
       [0.5108242 ],
       [0.5108242 ],
       [0.528088  ],
       [0.5489994 ],
       [0.5148672 ],
       [0.5051727 ],
       [0.5108242 ],
       [0.5275079 ],
       [0.5108242 ],
       [0.5142854 ],
       [0.5140002 ],
       [0.5142056 ],
       [0.5494267 ],
       [0.5179688 ],
       [0.5359174 ],
       [0.5179688 ],
       [0.514495  ],
       [0.5383166 ],
       [0.5222762 ],
       [0.52972615],
       [0.5406813 ],
       [0.51793736],
       [0.5051727 ],
       [0.5319263 ],
       [0.511721  ],
       [0.519

In [43]:
model = load_model('amazo.h5')

In [44]:
#save bag of word model
import joblib
joblib.dump(cv.vocabulary_,"amazo.save")

['amazo.save']

In [45]:
loaded=CountVectorizer(decode_error='replace',vocabulary=joblib.load('amazo.save'))

In [46]:
d="Writing was good"
d=d.split('delimiter')
result=model.predict(loaded.transform(d))
print(result)
prediction=result<0.5
#print(prediction)
if prediction[0] == False:
    print("Positive review")
elif prediction[0] == True:
    print("Negative review")

[[0.511721]]
Positive review
